### ISSUE TITLE
[Android] java.lang.NullPointerException in UnityNotificationRestartOnBootReceiver.java

### ISSUE THREAD

**Issue by artyom-v** [Unity-Technologies/com.unity.mobile.notifications#140]
Unity v2020.3.25f1
Plugin v1.5.0

`Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.unity.androidnotifications.UnityNotificationRestartOnBootReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4125)
       at android.app.ActivityThread.access$1400(ActivityThread.java:270)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2062)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference
       at com.unity.androidnotifications.UnityNotificationRestartOnBootReceiver.onReceive(UnityNotificationRestartOnBootReceiver.java:26)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4116)
       at android.app.ActivityThread.access$1400(ActivityThread.java:270)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2062)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)`

[data_intent](https://github.com/Unity-Technologies/com.unity.mobile.notifications/blob/f5251ebb3313d63bc84a0d6d40d56040923c9048/com.unity.mobile.notifications/Runtime/Android/Plugins/com/unity/androidnotifications/UnityNotificationRestartOnBootReceiver.java#L26) can be null in saved_notifications List

**Comment by aurimasc** [comment]
Fixed in master
