### ISSUE TITLE
[Android] java.lang.RuntimeException: invalid Icon type in parcel

### ISSUE THREAD

**Issue by artyom-v** [Unity-Technologies/com.unity.mobile.notifications#147]
Plugin v1.5.0
Unity v2020.3.26f1 il2cpp build

`Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.unity.androidnotifications.UnityNotificationRestartOnBootReceiver: java.lang.RuntimeException: invalid Icon type in parcel: 13
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4772)
       at android.app.ActivityThread.access$1800(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2294)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

Caused by java.lang.RuntimeException: invalid Icon type in parcel: 13
       at android.graphics.drawable.Icon.<init>(Icon.java:903)
       at android.graphics.drawable.Icon.<init>(Icon.java:71)
       at android.graphics.drawable.Icon$1.createFromParcel(Icon.java:945)
       at android.graphics.drawable.Icon$1.createFromParcel(Icon.java:943)
       at android.app.Notification$Action.<init>(Notification.java:1731)
       at android.app.Notification$Action.<init>(Notification.java:1607)
       at android.app.Notification$Action$1.createFromParcel(Notification.java:2134)
       at android.app.Notification$Action$1.createFromParcel(Notification.java:2132)
       at android.os.Parcel.readTypedObject(Parcel.java:3183)
       at android.os.Parcel.createTypedArray(Parcel.java:3144)
       at android.app.Notification.readFromParcelImpl(Notification.java:2572)
       at android.app.Notification.<init>(Notification.java:2498)
       at android.app.Notification$1.createFromParcel(Notification.java:3218)
       at android.app.Notification$1.createFromParcel(Notification.java:3215)
       at android.os.Parcel.readParcelable(Parcel.java:3345)
       at android.os.Parcel.readValue(Parcel.java:3238)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3635)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.Bundle.getParcelable(Bundle.java:1002)
       at android.content.Intent.getParcelableExtra(Intent.java:9180)
       at com.unity.androidnotifications.UnityNotificationRestartOnBootReceiver.onReceive(UnityNotificationRestartOnBootReceiver.java:26)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4763)
       at android.app.ActivityThread.access$1800(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2294)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)`

There are a lot of exceptions for different Android versions

**Comment by aurimasc** [comment]
Could you submit this bug with a repro project via Unity Editor?
It's not very usefull with only stack trace available.

**Comment by artyom-v** [comment]
Unfortunately, I can't reproduce this exception in a project on test devices. This exception was received through Firebase Crashlytics from users playing production build.
Notifications are created when the focus is lost (using AndroidNotificationCenter.SendNotification) and are removed on the application start or focus gain (using AndroidNotificationCenter.CancelAllNotifications())

**Comment by artyom-v** [comment]
Steps to reproduce:
1. Launch build and create scheduled notification with small icon.
2. Build new app version.
3. Update installed app with new version.
4. Wait for scheduled notification.
5. Observe exception in logcat.

Exception occured when Android trying to load small icon by resource id from previous app version and this id was changed in new app version.
The suggested fix is to catch PACKAGE_CHANGED intent action and recreate all notifications, so they will be with updated id.

**Comment by artyom-v** [comment]
MY_PACKAGE_REPLACED intent will be better
