### ISSUE TITLE
[Android] java.lang.NoSuchMethod exception: getActiveNotifications() is available only in API level 23 and later

### ISSUE THREAD

**Issue by artyom-v** [Unity-Technologies/com.unity.mobile.notifications#192]
Plugin v2.0.1
Unity v2020.3.34f1

The following exception has occurred on devices with Android less than 6.0
`Caused by java.lang.NoSuchMethodError: No virtual method getActiveNotifications()[Landroid/service/notification/StatusBarNotification; in class Landroid/app/NotificationManager; or its super classes (declaration of 'android.app.NotificationManager' appears in /system/framework/framework.jar:classes2.dex)
       at com.unity.androidnotifications.UnityNotificationManager.findInvalidNotificationIds(UnityNotificationManager.java:430)
       at com.unity.androidnotifications.UnityNotificationManager.performNotificationHousekeeping(UnityNotificationManager.java:403)
       at com.unity.androidnotifications.UnityNotificationManager.lambda$triggerHousekeeping$0(UnityNotificationManager.java:387)
       at com.unity.androidnotifications.-$$Lambda$UnityNotificationManager$fSttc7CuZmP-kDH-q_FquZSJ7Yk.run(lambda)
       at java.lang.Thread.run(Thread.java:818)`

Method getActiveNotifications() was added only in API level 23 (Android 6.0)

**Comment by abogarsukov-braingames** [comment]
This should be fixed in v2.0.2.
