### ISSUE TITLE
Failed to serialize Parcelable error on notification with emoji

### ISSUE THREAD

**Issue by sadegh-askari** [Unity-Technologies/com.unity.mobile.notifications#208]
Hi,
I tried to use emoji in text of my notifications. I created two notifications with emoji and with different delivery times.
The first time when the program is closed, the notification is displayed with emoji without any problem, but the next time I enter the program and the notifications set, when I want to close the app, these errors are displayed and notifications aren't delivered.

> 2022-07-06 13:29:15.747 29147-29219/? E/UnityNotifications: Failed to serialize Parcelable
    java.lang.RuntimeException: Tried to marshall a Parcel that contained Binder objects.
        at android.os.Parcel.nativeMarshall(Native Method)
        at android.os.Parcel.marshall(Parcel.java:480)
        at com.unity.androidnotifications.UnityNotificationUtilities.serializeParcelable(UnityNotificationUtilities.java:186)
        at com.unity.androidnotifications.UnityNotificationUtilities.serializeNotificationParcel(UnityNotificationUtilities.java:106)
        at com.unity.androidnotifications.UnityNotificationUtilities.serializeNotification(UnityNotificationUtilities.java:87)
        at com.unity.androidnotifications.UnityNotificationManager.saveNotification(UnityNotificationManager.java:496)
        at com.unity.androidnotifications.UnityNotificationManager.scheduleNotification(UnityNotificationManager.java:278)
        at com.unity3d.player.UnityPlayer.nativeFocusChanged(Native Method)
        at com.unity3d.player.UnityPlayer.access$000(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:179)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

> 2022-07-06 13:29:43.275 29336-29336/? E/UnityNotifications: Failed to deserialize notification
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification$Builder com.unity.androidnotifications.UnityNotificationManager.createNotificationBuilder(java.lang.String)' on a null object reference
        at com.unity.androidnotifications.UnityNotificationUtilities.deserializeNotificationCustom(UnityNotificationUtilities.java:325)
        at com.unity.androidnotifications.UnityNotificationUtilities.deserializeNotification(UnityNotificationUtilities.java:223)
        at com.unity.androidnotifications.UnityNotificationUtilities.deserializeNotification(UnityNotificationUtilities.java:203)
        at com.unity.androidnotifications.UnityNotificationManager.getNotificationOrBuilderForIntent(UnityNotificationManager.java:865)
        at com.unity.androidnotifications.UnityNotificationManager.onReceive(UnityNotificationManager.java:674)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3392)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

> 2022-07-06 13:29:43.276 29336-29336/? E/UnityNotifications: Failed to deserialize old style notification
    java.lang.IllegalStateException: Bad magic number for Bundle: 0x0
        at android.os.BaseBundle.readFromParcelInner(BaseBundle.java:1540)
        at android.os.BaseBundle.readFromParcelInner(BaseBundle.java:1525)
        at android.os.Bundle.readFromParcel(Bundle.java:1193)
        at com.unity.androidnotifications.UnityNotificationUtilities.deserializedFromOldIntent(UnityNotificationUtilities.java:378)
        at com.unity.androidnotifications.UnityNotificationUtilities.deserializeNotification(UnityNotificationUtilities.java:225)
        at com.unity.androidnotifications.UnityNotificationUtilities.deserializeNotification(UnityNotificationUtilities.java:203)
        at com.unity.androidnotifications.UnityNotificationManager.getNotificationOrBuilderForIntent(UnityNotificationManager.java:865)
        at com.unity.androidnotifications.UnityNotificationManager.onReceive(UnityNotificationManager.java:674)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3392)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Editor version: 2021.3.5 apple silicon
Target OS: android
Target Device: Samsung galaxy a5
Sdk version: 2.0.2

**Comment by aurimasc** [comment]
Should be fixed in latest master.
