### ISSUE TITLE
UnityNotificationUtilities.deserializeNotificationIntent

### ISSUE THREAD

**Issue by maccoop** [Unity-Technologies/com.unity.mobile.notifications#256]
Hi,
I'm using Mobile Notification v2.1.1, and app crash and log this in firebase, and crash on more Android OS
![image crash](https://user-images.githubusercontent.com/89531372/221080856-d3625c1f-18dc-436d-81c8-f64e6ec86557.png)

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.unity.androidnotifications.UnityNotificationRestartOnBootReceiver: java.lang.IllegalStateException: Bundle length is not aligned by 4: 1347308885
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4369)
       at android.app.ActivityThread.access$1600(ActivityThread.java:268)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2106)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7941)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003
```

**Comment by aurimasc** [comment]
The title and stacktrace look a bit detached. Could you provide corrected/more detailed info?
